const ROLES = {
  ADMIN: "Admin",
  CUSTOMER: "Customer",
};

const ORDER_STATUS = {
  PENDING: "PENDING",
  PAYMENT_INITIATED: "PAYMENT_INITIATED",
  PAID: "PAID",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  CANCELLED: "CANCELLED",
};

const ORDER_PAYMENT_STATUS = {
  PENDING: "PENDING",
  CREATED: "CREATED",
  AUTHORIZED: "AUTHORIZED",
  CAPTURED: "CAPTURED",
  FAILED: "FAILED",
  REFUNDED: "REFUNDED",
  PARTIALLY_REFUNDED: "PARTIALLY_REFUNDED",
};

const PAYMENT_STATUS = {
  CREATED: "CREATED",
  AUTHORIZED: "AUTHORIZED",
  CAPTURED: "CAPTURED",
  FAILED: "FAILED",
  REFUNDED: "REFUNDED",
  PARTIALLY_REFUNDED: "PARTIALLY_REFUNDED",
};

const PAYMENT_LOG_SOURCE = {
  APPLICATION: "APPLICATION",
  RAZORPAY_API: "RAZORPAY_API",
  FRONTEND_CALLBACK: "FRONTEND_CALLBACK",
  WEBHOOK: "WEBHOOK",
  SYSTEM: "SYSTEM",
};

const WEBHOOK_PROCESSING_STATUS = {
  RECEIVED: "RECEIVED",
  VERIFIED: "VERIFIED",
  PROCESSING: "PROCESSING",
  PROCESSED: "PROCESSED",
  IGNORED: "IGNORED",
  FAILED: "FAILED",
};

module.exports = {
  ROLES,
  ORDER_STATUS,
  ORDER_PAYMENT_STATUS,
  PAYMENT_STATUS,
  PAYMENT_LOG_SOURCE,
  WEBHOOK_PROCESSING_STATUS,
};
